version: '2'

services:
    web:
        build:
            context: .
            dockerfile: ./docker_config/dev/Dockerfile
        image: party_maker
        container_name: party_maker
        depends_on:
            - db1
        ports:
            - "9222:80"
        volumes:
            - ./app:/app
        env_file:
            - ./app/.envs/.app
        mem_limit: 1G
        restart: on-failure
    db1:
        image: postgres:latest
        container_name: Postgres-maker
        env_file:
            - ./app/.envs/.app
        expose:
            - "5432"
